import styled from "styled-components";
import  Head  from "next/head";
import type { ChildrenProp } from "../types/types";
import type { FC } from "react";
import { Navbar, Footer } from "./";

const Style = styled.div`
main{
  margin: 0 2em;
}
`;

const Layout = ({ children }: ChildrenProp) => {
  return (
    <Style>
      <Head>
        <title>Madames</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main>
        {children}
      </main>
      <footer>
        <Footer />
      </footer>
    </Style>
  )
}

export default Layout;